name: Update Tourism Data

on:
  schedule:
    - cron: '0 2 * * *'   # 매일 오전 2시 (UTC 기준, KST는 오전 11시) 실행
  workflow_dispatch:     # GitHub Actions 탭에서 수동 실행 가능하도록 설정

jobs:
  fetch-tour-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Fetch Tourism Data
        env:
          TOUR_API_KEY: ${{ secrets.TOUR_API_KEY }}
        run: |
          node scripts/fetch-tour-data.js

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # data 디렉토리가 없으면 생성 (안전 장치)
          mkdir -p data
          
          # 변경사항이 있는지 확인하고, 있다면 커밋 및 푸시
          # git add . 이후 git diff --staged --exit-code는 변경사항이 없으면 0, 있으면 1을 반환.
          # 따라서 변경사항이 있을 때만 커밋을 수행하도록 !를 붙여 조건을 반전.
          git add data/*.json
          if ! git diff --staged --quiet; then
            echo "Changes found. Committing and pushing..."
            git commit -m "Update tour data $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit. Working tree clean."
          fi
